Adding start page content for the docs
loklak/dev.loklak.org pull request #7
Opened 2017-05-12 06:20 UTC by imujjwal96

Related issue: #2 
In this repository, the raw file of various sub-projects will be added to the raw directory, with `raw/index.rst` being the raw file for the start page content.

Docs of sub-projects will be stored in `raw/SUB-PROJECT-NAME` 

## Screenshot
![image](https://cloud.githubusercontent.com/assets/8245662/25985510/7c5259be-3708-11e7-965e-e19bc8fe3944.png)

2017-05-12 07:10 UTC, sch00lb0y commented on raw/index.rst
> +-----------
you can give hyper link to all wrapper library

2017-05-12 07:15 UTC, pri22296 commented
@imujjwal96 The screenshot and the index.rst seems to not be in sync. They seem to have different toctrees. Can you attach a screenshot of the site built using the current index.rst

2017-05-12 07:23 UTC, imujjwal96 commented
The screenshot is in sync. The reason why you don't see the last 4 lines in the list is because the links doesn't exist for them and hence they weren't added.

2017-05-12 07:28 UTC, imujjwal96 commented on raw/index.rst
> +-----------
Where should the hyper link point to? I made the raw file as it was in the issue #2

2017-05-12 07:38 UTC, pri22296 requested changes

2017-05-12 07:38 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/server
Use relative link instead of absolute for linking to documentation of subproject

2017-05-12 07:38 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/search/
use relative link

2017-05-12 07:38 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/webapps/
use relative link

2017-05-12 07:38 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/androidwok/
use relative link

2017-05-12 07:38 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/desktopwok/
use relative link

2017-05-12 07:47 UTC, imujjwal96 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/server
I was a bit skeptical about it as these links don't actually exist right now. Maybe we can make these changes later when we have the documentation of these sub-projects in the repository.

2017-05-12 08:01 UTC, pri22296 approved these changes

2017-05-12 08:04 UTC, pri22296 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/server
@imujjwal96 we can make the required changes in a seperate PR after [#1127](https://github.com/loklak/loklak_server/pull/1127) gets merged.

2017-05-12 08:06 UTC, imujjwal96 commented on raw/index.rst
> +Documentation: http://dev.loklak.org/server
:+1:

2017-05-12 11:05 UTC, sch00lb0y commented on raw/index.rst
> +-----------
each library having their own repo https://github.com/loklak/loklak_go_api

2017-05-12 11:31 UTC, imujjwal96 commented on raw/index.rst
> +-----------
But then these APIs ought to have their own documentation. We can at a later stage, when their documentations are integrated, add links to both their github repository and their documentation the way we did with the other repositories.

2017-05-12 11:33 UTC, imujjwal96 commented on raw/index.rst
> +-----------
I think our primary focus at the moment should be to integrate everything. Such minor changes can me made afterwards.

2017-05-12 12:16 UTC, sch00lb0y commented on raw/index.rst
> +-----------
okay cool

2017-05-12 12:16 UTC, poonai approved these changes

2017-05-20 13:01 UTC, imujjwal96 commented
@mariobehling Still waiting for @yukiisbored's review

2017-05-20 13:13 UTC, yukiisbored requested changes
Please use relative links so it'll work locally, under any domain name, on someone else's computer, on my phone locally, etc.

2017-05-20 18:52 UTC, pri22296 reviewed
use rst directive `:doc:` to link to the specific `index.rst` file within subprojects.

2017-05-20 19:29 UTC, imujjwal96 commented
@pri22296 I'm sorry, but I don't exactly follow what I should change. Can you please elaborate it more?

2017-05-20 19:38 UTC, pri22296 commented
@imujjwal96 use ``:doc:`DOCUMENTATION <SUB-PROJECT/index>` `` instead of `` `DOCUMENTATION <SUB-PROJECT>`_``

2017-05-25 12:15 UTC, pri22296 commented
@imujjwal96 Please squash the commits. other than that LGTM

2017-05-27 16:04 UTC, pri22296 approved these changes

2017-05-28 03:58 UTC, yukiisbored commented
Please move it into `index.rst.d` and rename it to `00_readme.rst`

2017-05-30 17:28 UTC, merged